name: 🚀 Release to NPM

on:
  release:
    types: [published]

env:
  CI: true

jobs:
  test-release:
    name: 🎯 Test Release on Node ${{ matrix.node }} / TS ${{ matrix.typescript }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
        typescript:
          [
            '~4.7.4',
            '~4.8.3',
            '~4.9.5',
            '~5.0.4',
            '~5.1.6',
            '~5.2.2',
            '~5.3.3',
            '~5.4.2'
          ]
    steps:
      - name: ♻️ Checkout
        uses: actions/checkout@v4

      - name: 📌 Set shas
        uses: nrwl/nx-set-shas@v4

      - name: 🏗️ Set up pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: 🏗️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: 🚚 Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm add --save-dev typescript@${{ matrix.typescript }} -w
        shell: bash

      - name: 🎯 Run tests
        run: pnpm test-affected

  release:
    name: 🚀 Release
    environment: CI
    needs: test-release
    runs-on: ubuntu-latest
    steps:
      - name: ♻️ Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: 🏗️ Set up pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: 🏗️ Set up Node.js
        uses: actions/setup-node@v4

      - name: 🚚 Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: 🏗️ Build
        run: pnpm build

      - name: 📌 Set packages versions
        run: pnpm set-packages-versions ${{ github.event.release.tag_name }}

      - name: 🔄 Copy paste root README to @onion.js/core
        run: cp README.md ./packages/core/README.md

      - name: 🚀 Release (1/2)
        run: echo "RELEASE_NPM_TAG=${{ github.event.release.prerelease && 'alpha' ||  'latest' }}" >> $GITHUB_ENV

      - name: 🚀 Release (2/2)
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ env.RELEASE_NPM_TAG }}
          strategy: upgrade
          package: ./packages/core/package.json
